config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("tube.urls")),
    path('users', include("users.urls")),
    path('accounts/',include("allauth.urls")),# ←allauthのurls.pyを登録
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tube/urls.py
from django.urls import path
from . import views


app_name = "tube"
urlpatterns =[
    path('', views.index, name="index"),

    path('search/', views.search, name="search"),

    # TIPS:<型:変数名>とすることでビューに変数を与えることができる
    #idをuuidにするので、intをuuidに変える。

    path('single/<uuid:video_pk>/', views.single, name="single"),
    path('single_mod/<uuid:video_pk>/', views.single_mod, name="single_mod"),
    path('video_comment_reply/<uuid:comment_pk>/', views.video_comment_reply, name="video_comment_reply"),
    path('video_comment_reply_to_reply/<uuid:videocommentreply_pk>/', views.video_comment_reply_to_reply, name="video_comment_reply_to_reply"),
    path('video_comment_edit/<uuid:comment_pk>/', views.video_comment_edit, name="video_comment_edit"),
    path('video_comment_reply_edit/<uuid:reply_pk>/', views.video_comment_reply_edit, name="video_comment_reply_edit"),

    ##ランキングページ。DBからデータ抜き取って表示するだけ。GET文だけ
    path('rank/', views.rank, name="rank"),
    path('user_policy', views.user_policy, name="user_policy"),

    # 以下認証済みユーザー専用
    path('mypage/', views.mypage, name="mypage"),
    path('history/', views.history, name="history"),
    path('recommend/', views.recommend, name="recommend"),
    path('notify/', views.notify, name="notify"),
    path('mylist/', views.mylist, name="mylist"),
    path('upload', views.upload, name="upload"),
    path('config/', views.config, name="config"),


    path('usersingle/<uuid:pk>/', views.usersingle, name="usersingle"),
    path('userfollow/<uuid:pk>/', views.userfollow, name="userfollow"),
    path('userblock/<uuid:pk>/', views.userblock, name="userblock"),
    path('useredit/<uuid:pk>/', views.useredit, name="useredit"),
]

tube/views.py
from rest_framework import status,views,response

from django.shortcuts import render, redirect

from django.db.models import Q,Count

from django.http.response import JsonResponse

from django.template.loader import render_to_string

from django.core.paginator import Paginator

from django.conf import settings

#TIPS:ログイン状態かチェックする。ビュークラスに継承元として指定する(多重継承なので順番に注意)。未ログインであればログインページへリダイレクト。
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone

from .models import Video,Category,VideoComment,VideoCommentReply,VideoCommentReplyToReply,MyList,History,GoodVideo

from users.models import CustomUser,FollowUser,BlockUser

from .serializer import VideoSerializer,VideoEditSerializer,VideoCommentSerializer,VideoCommentEditSerializer,VideoCommentReplyEditSerializer,VideoCommentReplySerializer,VideoCommentReplyToReplySerializer,MyListSerializer,HistorySerializer,RateSerializer,GoodSerializer,IconSerializer,FollowUserSerializer,BlockUserSerializer,UserInformationSerializer

DEFAULT_VIDEO_AMOUNT = 10
COMMENTS_AMOUNT_PAGE = 10

#python-magicで受け取ったファイルのMIMEをチェックする。
#MIMEについては https://developer.mozilla.org/ja/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types を参照。

from PIL import Image
import qrcode
from io import BytesIO
import base64

import magic
ALLOWED_MIME   = ["video/mp4"]

# アップロードの上限
LIMIT_SIZE     = 200 * 1000 * 1000

SEARCH_AMOUNT_PAGE  = 20

#トップページ
class IndexView(views.APIView):

    def get(self, request,*args, **kwargs):

        # 新着順
        latests = Video.objects.all().order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]
        latests = Video.objects.annotate(num_comments=Count("videocomment", distinct=True),num_mylists=Count("mylist", distinct=True)).all().order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

        if request.user.is_authenticated:

            # 最近見た動画
            histories = History.objects.filter(user=request.user.id).exclude(target__user__blocked=request.user.id).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

            hist_id_list   = []
            for history in histories:
                hist_id_list.append(history.target.id)

            histories = Video.objects.annotate(num_comments=Count("videocomment", distinct=True),num_mylists=Count("mylist", distinct=True)).filter(id__in=hist_id_list).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

            # フォローユーザーの動画
            follows = Video.objects.filter(user__followed=request.user.id).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]
            follows = Video.objects.annotate(num_comments=Count("videocomment", distinct=True),num_mylists=Count("mylist", distinct=True)).filter(user__followed=request.user.id).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

            # 新着順(ブロックしたユーザーは除外)
            latests = Video.objects.exclude(user__blocked=request.user.id).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

            latests = Video.objects.annotate(num_comments=Count("videocomment", distinct=True),num_mylists=Count("mylist", distinct=True)).exclude(user__blocked=request.user.id).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]
            # これで動画一覧表示時に、マイリス数とコメント数をセットで表示できる。

        else:
            histories = False
            follows = False

        context = {"latests": latests,
                   "histories": histories,
                   "follows": follows,
                   }

        return render(request, "tube/index.html", context)

index = IndexView.as_view()

#アップロードページ
class UploadView(LoginRequiredMixin,views.APIView):

    def get(self,request, *args, **kwargs):

        categories = Category.objects.all()
        context = {"categories": categories}

        return render(request, "tube/upload.html", context)


    def post(self, request, *args, **kwargs):

        print(request.data)

        request.data["user"]    = request.user.id
        serializer              = VideoSerializer(data=request.data)
        mime_type               = magic.from_buffer(request.FILES["movie"].read(1024), mime=True)

        print(request.data["movie"].size)
        print(type(request.data["movie"].size))

        if request.FILES["movie"].size >= LIMIT_SIZE:
            mb = str(LIMIT_SIZE / 1000000)

            json = {"error": True,
                    "message": "The maximum file size is " + mb + "MB"}

            return JsonResponse(json)

        if mime_type not in ALLOWED_MIME:
            mime = str(ALLOWED_MIME)
            json = {"error": True,
                    "message": "The file you can post is " + mime + "."}

            return JsonResponse(json)

        if serializer.is_valid():
            serializer.save()
        else:
            json    = { "error":True,
                        "message":"入力内容に誤りがあります。" }
            return JsonResponse(json)

        json    = { "error":False,
                    "message":"アップロード完了しました。" }

        return JsonResponse(json)


upload = UploadView.as_view()



#検索結果表示ページ
class SearchView(views.APIView):

    def get(self, request, *args, **kwargs):

        query = Q()
        page = 1

        if "word" in request.GET:

            word_list = request.GET["word"].replace("　", " ").split(" ")
            for w in word_list:
                query &= Q(Q(title__icontains=w) | Q(description__icontains=w))

        if "page" in request.GET:
            page = request.GET["page"]

        # TODO:ここでログインしていれば、ブロックユーザーを除外した検索をする。
        if request.user.is_authenticated:
            videos = Video.objects.filter(query).exclude(user__blocked=request.user.id).order_by("-dt")

            videos = Video.objects.filter(query).annotate(num_comments=Count("videocomment", distinct=True),num_mylists=Count("mylist", distinct=True)).exclude(user__blocked=request.user.id).order_by("-dt")

        else:
            videos = Video.objects.filter(query).order_by("-dt")

        amount = len(videos)

        videos_paginator = Paginator(videos, SEARCH_AMOUNT_PAGE)
        videos           = videos_paginator.get_page(page)

        context = {"videos": videos,
                   "amount": amount}

        return render(request, "tube/search.html", context)

search = SearchView.as_view()


#動画個別ページ
class SingleView(views.APIView):

    def get(self,request, video_pk,*args, **kwargs):

        print(request.user.username)

        video = Video.objects.filter(id=video_pk).first()

        blockeduser = CustomUser.objects.filter(blocked=video.user.id)
        print(blockeduser)

        if request.user in blockeduser:
            print("ブロックされています")
            return redirect( "tube:index" )
        else:
            print("ブロックされていません")

        #Todo:F5で再生回数水増し可能。
        video.views = video.views + 1
        video.save()

        if request.user.is_authenticated:
            print("認証済みユーザーです")

            history = History.objects.filter(user=request.user.id, target=video_pk).first()

            if history:
                print("存在する場合の処理")
                history.views   = history.views + 1
                history.dt      = timezone.now()
                history.save()
            else:
                print("履歴に存在しない場合の処理")
                data        = { "target":video_pk,
                                "user":request.user.id,}
                serializer  = HistorySerializer(data=data)

                if serializer.is_valid():
                    serializer.save()


        img   = qrcode.make(request.build_absolute_uri()) #動画のQRコード
        buffer = BytesIO()
        img.save(buffer, format="PNG")
        qr = base64.b64encode(buffer.getvalue()).decode().replace("'", "")

        counts = Video.objects.annotate(num_comments=Count("videocomment", distinct=True),num_mylists=Count("mylist", distinct=True)).filter(id=video_pk).first()

        comments = VideoComment.objects.filter(target=video_pk).order_by("-dt")
        comments = VideoComment.objects.annotate(num_reply=Count("videocommentreply", distinct=True)).filter(target=video_pk).order_by("-dt")

        good        = GoodVideo.objects.filter(target=video_pk)
        already_good    = GoodVideo.objects.filter(target=video_pk, user=request.user.id)

        relates         = Video.objects.filter(category=video.category).prefetch_related('category').order_by("-dt")

        mylist          = MyList.objects.filter(target=video_pk)
        already_mylist  = MyList.objects.filter(target=video_pk, user=request.user.id)

        categories      = Category.objects.all()

        paginator = Paginator(comments, 10)
        comments = paginator.get_page(1)

        context = {"video": video,
                   "comments": comments,
                   "good": good,
                   "already_good": already_good,
                   "mylist":mylist,
                   "already_mylist":already_mylist,
                   "relates": relates,
                   "qr":qr,
                   "counts":counts,
                   "categories":categories,
                   }

        return render(request, "tube/single/single.html", context)


single = SingleView.as_view()


class SingleModView(LoginRequiredMixin,views.APIView):

    #ここでコメントのページネーション↑ のクラス名変えるべきでは？
    def get(self,request,video_pk,*args,**kwargs):

        page        = 1
        if "page" in request.GET:
            page    = request.GET["page"]

        video               = Video.objects.filter(id=video_pk).first()
        comments            = VideoComment.objects.filter(target=video_pk).order_by("-dt")
        comments            = VideoComment.objects.annotate(num_reply=Count("videocommentreply", distinct=True)).filter(target=video_pk).order_by("-dt")

        comments_paginator  = Paginator(comments,COMMENTS_AMOUNT_PAGE)
        comments            = comments_paginator.get_page(page)




templates/tube/single/comments.html
{% load param_change %}
{% load static %}

{% for comment in comments %}
<div class="comment_video_sub_inner">

    <div class="comment_video_sub_inner_left">
        <a href="{% url 'tube:usersingle' comment.user.id %}">
            {% if comment.user.usericon %}
                <div><img class="video_usericon" src="{{ comment.user.usericon.url }}" alt="icon"></div>
            {% else %}
                <div><img class="video_usericon" src="{% static 'tube/img/non_usericon.png' %}" alt="{{ icon }}"></div>
            {% endif %}
        </a>
    </div>



    <div class="comment_video_sub_inner_right">

        <a href="{% url 'tube:usersingle' comment.user.id %}"><div> {{ comment.user.handle_name }} </div></a>

        {# コメント編集、削除、通報ボタン表示 #}
        <input id="comment_edit_menu_{{ comment.id }}" class="comment_edit_menu_button" type="checkbox">
            <label class="comment_edit_label" for="comment_edit_menu_{{ comment.id }}">
                <i class="fas fa-ellipsis-h"></i>
            </label>

            <input id="edit_{{ comment.id }}" type="checkbox" class="v_c_edit_tab" name="v_c_edit_tab" value="{{ comment.id }}">

            {% if request.user.id == comment.user.id %}
                {# 編集ボタン #}
                <label for="edit_{{ comment.id }}" class="v_c_edit_tab_label edit_menu1" value="{{ comment.id }}"><i class="far fa-edit"></i></label>

                {# コメント削除フォーム #}
                <form class="v_comment_delete_form_{{ comment.id}} edit_menu2" action="{% url 'tube:video_comment_edit' comment.id %}" method="delete">
                    <input id="v_c_delete1_{{ comment.id }}" type="button" class="v_c_delete_button" value="{{ comment.id }}"><label for="v_c_delete1_{{ comment.id }}" class="v_c_edit_tab_label"><i class="fas fa-eraser"></i></label>
                </form>

            {% elif request.user.id == comment.target.user.id %}
                {# コメント削除フォーム #}
                <form class="v_comment_delete_form_{{ comment.id}} edit_menu1" action="{% url 'tube:video_comment_edit' comment.id %}" method="delete">
                    <input id="v_c_delete2_{{ comment.id }}" type="button" class="v_c_delete_button" value="{{ comment.id }}"><label for="v_c_delete2_{{ comment.id }}" class="v_c_edit_tab_label"><i class="fas fa-eraser"></i></label>
                </form>

                {# 通知ボタン #}
                <input id="notice1_{{ comment.id }}" type="checkbox" class="v_c_notice_tab" name="v_c_notice_tab"><label for="notice1_{{ comment.id }}" class="v_c_notice_tab_label edit_menu2"><i class="fas fa-bell"></i></label>
            {% else %}
                {# 通知ボタン #}
                <input id="notice2_{{ comment.id }}" type="checkbox" class="v_c_notice_tab" name="v_c_notice_tab"><label for="notice2_{{ comment.id }}" class="v_c_notice_tab_label edit_menu1"><i class="fas fa-bell"></i></label>
            {% endif %}

        {# コメント内容#}
        <div class="v_comment_content" id="v_comment_content_{{ comment.id }}">{{ comment.content|linebreaksbr|urlize }}</div>

        {# コメント編集フォーム#}
        <div id="v_c_edit_message_{{ comment.id}}" class="js_message"></div>

        <form id="v_comment_update_form_{{ comment.id }}" class="v_comment_update_form" name="v_comment_update_form_{{ comment.id }}" action="{% url 'tube:video_comment_edit' comment.id %}">
            {% csrf_token %}
            <textarea class="textarea_form" name="content" placeholder="コメント編集" maxlength="500">{{ comment.content }}</textarea>
            <button class="v_c_edit_button btn btn-outline-primary btn-sm" value="{{ comment.id }}" type="button"><i class="far fa-paper-plane"></i></button>
        </form>


        <form id="v_c_notice_form_{{ comment.id }}" class="v_c_notice_form">
            {% csrf_token %}
            <textarea class="textarea_form" name="notice" placeholder="報告理由をお書きください。" maxlength="500"></textarea>
            <button class="v_c_edit_button btn btn-outline-primary btn-sm" value="{{ comment.id }}" type="button"><i class="far fa-paper-plane"></i></button>
        </form>

        <div class="video_comment_dt">{{ comment.dt|date:"Y-m-d h時" }} &nbsp;<i class="far fa-comment"></i>{{ comment.num_reply }}&nbsp;</div>

        <!--TIPS:コメントはループするのでidが重複してしまう。id属性の指定は禁止 ←ただし、UUIDを噛ませることで重複を防ぐことができる。-->
        <input id="reply_button_{{ comment.id }}" class="reply_chk" type="checkbox"><label class="reply_label" for="reply_button_{{ comment.id }}">返信</label>


        <div class="reply_area">
            <form id="reply_form_{{ comment.id }}" action="{% url 'tube:video_comment_reply' comment.id  %}" method="POST">
                {% csrf_token %}
                <textarea class="textarea_form" name="content" placeholder="返信" raws="1"></textarea>
                <button class="reply_submit btn btn-outline-primary btn-sm" value="{{ comment.id }}" type="button"><i class="far fa-paper-plane"></i></button>
            </form><br class="my-2">
            <div id="reply_content_{{ comment.id }}"><!--TODO:ここにリプライがJSによりレンダリングされる--></div>
        </div>

        <label id="edit_menu_closer" class="edit_menu_closer" for="comment_edit_menu_{{ comment.id }}"></label>

    </div>






</div>
{% endfor %}

{% if comments %}
<form id="comment_pagination_area" action="{% url 'tube:single_mod' video.id %}" method="GET">
    {% generate_pagelink_ajax request "page" "1" comments.paginator.num_pages comments.number %}
</form>

{% endif %}


templates/tube/single/comments_reply_to_reply.html
{% for reply in replies %}
{% load static %}

<div class="s_video_sub_inner">

    <div class="s_video_sub_inner_left">
        <a href="{% url 'tube:usersingle' reply.user.id %}">
            {% if reply.user.usericon %}
                <div><img class="video_usericon" src="{{ reply.user.usericon.url }}" alt="icon"></div>
            {% else %}
                <div><img class="video_usericon" src="{% static 'tube/img/non_usericon.png' %}" alt="{{ icon }}"></div>
            {% endif %}
        </a>
    </div>

    <div class="s_video_sub_inner_right">
        <a href="{% url 'tube:usersingle' reply.user.id %}"><div> {{ reply.user.handle_name }} </div></a>
        <div>{{ reply.content|linebreaksbr|urlize }}</div>
        <div class="video_comment_dt">{{ reply.dt|date:"Y-m-d h時" }}</div>
    </div>
</div>
{% endfor %}

templates/tube/single/rate.html
<form class="single_video_rating_content" action="{% url 'tube:single_mod' video.id %}">
    {% csrf_token %}
    <i class="far fa-thumbs-up single_video_rating_button rating_good {% if already_good %}already_good{% endif %}"></i>
    <span class="rating_num">{{ good|length }}</span>
</form>


<form class="single_video_rating_content" action="{% url 'tube:single_mod' video.id %}">
    {% csrf_token %}
    <i class="far fa-list-alt single_video_rating_button mylist_entry {% if already_mylist %}already_mylist{% endif %}"></i>
    <span class="rating_num">{{ mylist|length }}</span>
</form>


templates/tube/single/single.html
{% extends "tube/base.html" %}
{% load humanize %}
{% load static %}
{% load param_change %}

{% block site_title %}TubeIntegrity{% endblock %}


{% block extra_head %}
{{ block.super }}

<!--video.jsのCDNを読み込む-->
<link href="https://vjs.zencdn.net/7.11.4/video-js.css" rel="stylesheet" />
<script src="https://vjs.zencdn.net/7.11.4/video.min.js"></script>

<!--video.jsのカスタムスキンを指定-->
<link rel="stylesheet" href="{% static 'tube/css/videojs.css' %}">

<script src="{% static 'tube/js/single.js' %}"></script>

{% endblock %}



{% block page_title %}TubeIntegrity{% endblock %}

{% block main %}

         {% include "tube/search_form.html" %}

    <div class="single_video_area">
        <div class="single_video_content">
            <div class="single_video_content_inner">
                <video id="video-js" class="single_video video-js vjs-default-skin vjs-big-play-centered vjs-16-9">
                    <source src="{{ video.movie.url }}" type="video/mp4">
                </video>
                {% comment %}
                <button  class="skip" value="-10">Rewind</button>
                <button  class="skip" value="10">Fastforward</button>
                {% endcomment %}
            </div>


        </div>

        <div class="single_video_subcontent">
            <div class="single_video_subcontent_inner">

                <input id="subcontent_tab_1" class="subcontent_tab_radio" type="radio" name="subcontent_tab" checked><label for="subcontent_tab_1" class="subcontent_tab_label">説明</label>
                <input id="subcontent_tab_2" class="subcontent_tab_radio" type="radio" name="subcontent_tab"><label for="subcontent_tab_2" class="subcontent_tab_label">コメント</label>
                <input id="subcontent_tab_3" class="subcontent_tab_radio" type="radio" name="subcontent_tab"><label for="subcontent_tab_3" class="subcontent_tab_label">関連動画</label>

                {% if request.user == video.user %}
                <input id="subcontent_tab_4" class="subcontent_tab_radio" type="radio" name="subcontent_tab"><label for="subcontent_tab_4" class="subcontent_tab_label">投稿者オプション</label>
                {% endif %}

                <div class="single_video_description">

                    <div class="s_video_sub_inner">
                        <div class="s_video_sub_inner_left">
                            {% if video.user.usericon %}
                            <a href="{% url 'tube:usersingle' video.user.id %}"><img class="video_usericon" src="{{ video.user.usericon.url }}" alt="icon"></a>
                            {% else %}
                            <a href="{% url 'tube:usersingle' video.user.id %}"><img class="video_usericon" src="{% static 'tube/img/non_usericon.png' %}" alt="{{ icon }}"></a>
                            {% endif %}
                        </div>

                        <div class="s_video_sub_inner_right">
                            <div class="video_title">{{ video.title }}</div>
                            <a href="{% url 'tube:usersingle' video.user.id %}"><div>{{ video.user.handle_name }} </div></a>

                            <div class="video_value">
                                <span class="v_value_span"><i class="far fa-play-circle"></i>{{ video.views|intcomma }}</span>
                                <span class="v_value_span"><i class="far fa-comment"></i>{{ counts.num_comments }}</span>
                                <span class="v_value_span"><i class="far fa-list-alt"></i>{{ counts.num_mylists }}</span>
                            </div>

                            <div>{{ video.dt|date:"Y年m月d日 H時i分s秒" }}</div>
                            <div>{{ video.category }}</div>
                        </div>
                    </div>


                        {# 投稿者のフォロー。認証済みかつ投稿者以外のユーザーにだけフォローボタンを表示させる。本人のものは表示させない#}

                            {% if request.user.is_authenticated and request.user.id != video.user.id %}
                            <form id="follow_user_form" action="{% url 'tube:userfollow' video.user.id  %}" method="POST">
                                {% if request.user in video.user.followed.all %}
                                <button class="follow btn btn-primary" type="button">フォロー中</button>
                                {% else %}
                                <button class="follow btn btn-outline-primary" type="button">フォローする</button>
                                {% endif %}
                            </form>
                            {% endif %}



                        {% if request.user.is_authenticated and request.user.id != video.user.id %}
                        <form id="block_user_form" action="{% url 'tube:userblock' video.user.id  %}" method="POST">
                            {% if request.user in video.user.blocked.all %}
                            <button class="block btn btn-danger" type="button">ブロック中</button>
                            {% else %}
                            <button class="block btn btn-outline-danger" type="button">ブロックする</button>
                            {% endif %}
                        </form>
                        {% endif %}


                    <div id="mylist_message" class="js_message"></div>
                    <div class="single_video_mod_area">
                        <div id="single_video_rating_area" class="single_video_rating_area">
                            {% include "tube/single/rate.html" %}
                        </div>
                    </div>

                    <div>{{ video.description|linebreaksbr }}
                        {% if video.edited %}
                            <p class="sort"><i class="far fa-edit"></i></p>
                        {% endif %}
                    </div></br>


                    <input id="qr_code_box" class="qr_code_button" type="checkbox"><label for="qr_code_box" class="qr_code_label">QRコード</label>
                    <img class="qr_code" src="data:image/png;base64,{{ qr }}" alt="{{ request.build_absolute_uri }}"/>

                </div>

                <div class="single_video_comments">
                     <div id="comments_message" class="js_message"></div>

                     <form id="single_video_comments_form" action="{% url 'tube:single_mod' video.id %}" method="POST" >
                         {% csrf_token %}
                         <textarea class="textarea_form" name="content" placeholder="コメント" rows="1" maxlength="500"></textarea>
                         {# <input id="single_video_comments_submit" class="btn-gradient-radius" type="button" value="送信"> #}
                         <button id="single_video_comments_submit" class="v_c_subumit_button btn btn-outline-primary btn-sm" type="button"><i class="far fa-paper-plane"></i></button>
                     </form><br>

                     <div id="video_comments_area">
                         {% include "tube/single/comments.html" %}
                     </div>


                </div>

                <div class="single_video_relate">

                    {% for relate in relates %}
                    <a class="video_content_link" href="{% url 'tube:single' relate.id %}">
                        {% if relate.thumbnail %}
                        <img class="video_thumbnail" src="{{ relate.thumbnail.url }}" alt="{{ relate.title }}">
                        {% else %}
                        <img class="video_thumbnail" src="{% static 'tube/img/no-img.png' %}" alt="{{ relate.title }}">
                        {% endif %}
                    </a>

                    <div class="index_video_content_inner">

                        <div class="index_video_content_inner_left">
                             {% if relate.user.usericon %}
                            <a href="{% url 'tube:usersingle' relate.user.id %}"><img class="index_usericon" src="{{ relate.user.usericon.url }}" alt="icon"></a>
                            {% else %}
                            <a href="{% url 'tube:usersingle' relate.user.id %}"><img class="index_usericon" src="{% static 'tube/img/non_usericon.png' %}" alt="{{ icon }}"></a>
                            {% endif %}
                        </div>

                        <div class="index_video_content_inner_right">
                            <a href="{% url 'tube:single' relate.id %}"><div class="video_title">{{ relate.title }}</div></a>
                            <a href="{% url 'tube:usersingle' relate.user.id %}"><div>{{ relate.user.handle_name }} </div></a>
                            <div class="video_value">
                                <span class="v_value_span"><i class="far fa-play-circle"></i>{{ relate.views|intcomma }}</span>
                                <span>{{ relate.dt|date:"Y年m月d日" }}</span>
                            </div>

                        </div>
                    </div>

                    {% empty %}
                    <div class="video_content">動画がありません</div>

                    {% endfor %}

                </div>

                {% if request.user == video.user %}
                <div class="single_video_uploader">
                    <div>

                        {% if video.user.usericon %}
                        <a href="{% url 'tube:usersingle' video.user.id %}"><img class="video_usericon" src="{{ video.user.usericon.url }}" alt="icon"></a>
                        {% else %}
                        <a href="{% url 'tube:usersingle' video.user.id %}"><img class="video_usericon" src="{% static 'tube/img/non_usericon.png' %}" alt="{{ icon }}"></a>
                        {% endif %}

                        <a href="{% url 'tube:usersingle' video.user.id %}"><div>{{ video.user.handle_name }}</div></a>


                        <input id="edit_tab_1" class="edit_tab_radio" type="radio" name="edit_tab" checked><label for="edit_tab_1" class="edit_tab_label">編集</label>
                        <input id="edit_tab_2" class="edit_tab_radio" type="radio" name="edit_tab"><label for="edit_tab_2" class="edit_tab_label">削除</label>

                            <div class="edit_form">
                                <h3>投稿欄編集</h3>
                                <p>カテゴリー/タイトル/概要欄の編集ができます。</p>
                                <!-- Ajax でPUTメソッドを送信 -->
                                <form id="video_update_form" action="{% url 'tube:single_mod' video.id %}" >
                                    {% csrf_token %}

                                    <select class="select_form" name="category">
                                        <option value="">カテゴリを選択してください</option>
                                        {% for category in categories %}
                                        <option value="{{ category.id }}" {% if category.id == video.category.id %}selected{% endif %}>{{ category.name }}</option>
                                        {% empty %}
                                        <option value="">カテゴリがありません。</option>
                                        {% endfor %}
                                    </select>

                                    <input class="input_form_text" type="text" value="{{ video.title }}" name="title" placeholder="タイトル...">
                                    <textarea class="textarea_form" name="description" rows="4" placeholder="概要欄...">{{ video.description }}</textarea>
                                    <input id="video_update" class="btn-gradient-success" type="button" value="編集">
                                </form>
                            </div>

                            <div class="delete_form">

                                <!-- Ajax でDELETEメソッドを送信 -->
                                <form id="video_delete_form" action="{% url 'tube:single_mod' video.id %}" method="delete">
                                    {% csrf_token %}
                                    <h3>動画削除欄</h3>
                                    <p>この動画を削除しますか？</p>
                                    <input id="video_delete" class="btn-gradient-delete" type="button" value="削除">
                                </form>
                            </div>

                            <div id="delete_message" class="js_message"></div>

                    </div>
                </div>
                {% endif %}

            </div>
        </div>
    </div>

{% endblock %}