config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("tube.urls")),
    path('users', include("users.urls")),
    path('accounts/',include("allauth.urls")),# ←allauthのurls.pyを登録
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tube/urls.py
from django.urls import path
from . import views


app_name = "tube"
urlpatterns =[
    path('', views.index, name="index"),

    path('search/', views.search, name="search"),

    # TIPS:<型:変数名>とすることでビューに変数を与えることができる
    #idをuuidにするので、intをuuidに変える。

    path('single/<uuid:video_pk>/', views.single, name="single"),
    path('single_mod/<uuid:video_pk>/', views.single_mod, name="single_mod"),
    path('video_comment_reply/<uuid:comment_pk>/', views.video_comment_reply, name="video_comment_reply"),
    path('video_comment_reply_to_reply/<uuid:videocommentreply_pk>/', views.video_comment_reply_to_reply, name="video_comment_reply_to_reply"),
    path('video_comment_edit/<uuid:comment_pk>/', views.video_comment_edit, name="video_comment_edit"),
    path('video_comment_reply_edit/<uuid:reply_pk>/', views.video_comment_reply_edit, name="video_comment_reply_edit"),

    ##ランキングページ。DBからデータ抜き取って表示するだけ。GET文だけ
    path('rank/', views.rank, name="rank"),
    path('user_policy', views.user_policy, name="user_policy"),

    # 以下認証済みユーザー専用
    path('mypage/', views.mypage, name="mypage"),
    path('history/', views.history, name="history"),
    path('recommend/', views.recommend, name="recommend"),
    path('notify/', views.notify, name="notify"),
    path('mylist/', views.mylist, name="mylist"),
    path('upload', views.upload, name="upload"),
    path('config/', views.config, name="config"),


    path('usersingle/<uuid:pk>/', views.usersingle, name="usersingle"),
    path('userfollow/<uuid:pk>/', views.userfollow, name="userfollow"),
    path('userblock/<uuid:pk>/', views.userblock, name="userblock"),
    path('useredit/<uuid:pk>/', views.useredit, name="useredit"),
]

templates/common/sidebar.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{% block site_title %}TubeIntegrity{% endblock %}</title>

    <!--静的ファイルの読み込みは html冒頭でload staticのテンプレートタグを記述した後、下記のように読み込み指定する。-->
    <link rel="stylesheet" href="{% static 'common/css/l_sidebar.css' %}">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <script src="{% static 'common/js/jquery-3.1.1.min.js' %}"></script>

    <script src="{% static 'common/js/l_sidebar.js' %}"></script>

    <link rel="stylesheet" href="{% static 'common/css/fontawesome/all.css' %} ">

    {% block extra_head %}
    {% endblock %}

</head>
<body>

    <header>

        <input id="l_sidebar" class="l_sidebar_button" type="checkbox">

        <div class="left_header">
            <label class="l_sidebar_label" for="l_sidebar">
                <i class="fas fa-bars"></i>
                <i class="fas fa-times"></i>
            </label>
            <a class="header_link" href="{% url 'tube:index' %}"><h1>{% block header_title %}{% endblock %}</h1></a>
            <div class="header_right_content">
            {% block header_right_content %}
            {% endblock %}
            </div>
        </div>

        <div class="l_sidebar_menu">
            {% block sidebar_content %}{% endblock %}
        </div>

        <div id="l_sidebar_closer" class="l_sidebar_closer"></div>


    </header>


    <main>
    {% block main %}
    {% endblock %}
    </main>



</body>
</html>

