config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("tube.urls")),
    path('users', include("users.urls")),
    path('accounts/',include("allauth.urls")),# ←allauthのurls.pyを登録
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tube/urls.py
from django.urls import path
from . import views


app_name = "tube"
urlpatterns =[
    path('', views.index, name="index"),

    path('search/', views.search, name="search"),

    # TIPS:<型:変数名>とすることでビューに変数を与えることができる
    #idをuuidにするので、intをuuidに変える。

    path('single/<uuid:video_pk>/', views.single, name="single"),
    path('single_mod/<uuid:video_pk>/', views.single_mod, name="single_mod"),
    path('video_comment_reply/<uuid:comment_pk>/', views.video_comment_reply, name="video_comment_reply"),
    path('video_comment_reply_to_reply/<uuid:videocommentreply_pk>/', views.video_comment_reply_to_reply, name="video_comment_reply_to_reply"),
    path('video_comment_edit/<uuid:comment_pk>/', views.video_comment_edit, name="video_comment_edit"),
    path('video_comment_reply_edit/<uuid:reply_pk>/', views.video_comment_reply_edit, name="video_comment_reply_edit"),

    ##ランキングページ。DBからデータ抜き取って表示するだけ。GET文だけ
    path('rank/', views.rank, name="rank"),
    path('user_policy', views.user_policy, name="user_policy"),

    # 以下認証済みユーザー専用
    path('mypage/', views.mypage, name="mypage"),
    path('history/', views.history, name="history"),
    path('recommend/', views.recommend, name="recommend"),
    path('notify/', views.notify, name="notify"),
    path('mylist/', views.mylist, name="mylist"),
    path('upload', views.upload, name="upload"),
    path('config/', views.config, name="config"),


    path('usersingle/<uuid:pk>/', views.usersingle, name="usersingle"),
    path('userfollow/<uuid:pk>/', views.userfollow, name="userfollow"),
    path('userblock/<uuid:pk>/', views.userblock, name="userblock"),
    path('useredit/<uuid:pk>/', views.useredit, name="useredit"),
]

tube/views.py
from rest_framework import status,views,response

from django.shortcuts import render, redirect

from django.db.models import Q,Count

from django.http.response import JsonResponse

from django.template.loader import render_to_string

from django.core.paginator import Paginator

from django.conf import settings

#TIPS:ログイン状態かチェックする。ビュークラスに継承元として指定する(多重継承なので順番に注意)。未ログインであればログインページへリダイレクト。
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone

from .models import Video,Category,VideoComment,VideoCommentReply,VideoCommentReplyToReply,MyList,History,GoodVideo

from users.models import CustomUser,FollowUser,BlockUser

from .serializer import VideoSerializer,VideoEditSerializer,VideoCommentSerializer,VideoCommentEditSerializer,VideoCommentReplyEditSerializer,VideoCommentReplySerializer,VideoCommentReplyToReplySerializer,MyListSerializer,HistorySerializer,RateSerializer,GoodSerializer,IconSerializer,FollowUserSerializer,BlockUserSerializer,UserInformationSerializer

DEFAULT_VIDEO_AMOUNT = 10
COMMENTS_AMOUNT_PAGE = 10

#python-magicで受け取ったファイルのMIMEをチェックする。
#MIMEについては https://developer.mozilla.org/ja/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types を参照。

from PIL import Image
import qrcode
from io import BytesIO
import base64

import magic
ALLOWED_MIME   = ["video/mp4"]

# アップロードの上限
LIMIT_SIZE     = 200 * 1000 * 1000

SEARCH_AMOUNT_PAGE  = 20

#トップページ
class IndexView(views.APIView):

    def get(self, request,*args, **kwargs):

        # 新着順
        latests = Video.objects.all().order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]
        latests = Video.objects.annotate(num_comments=Count("videocomment", distinct=True),num_mylists=Count("mylist", distinct=True)).all().order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

        if request.user.is_authenticated:

            # 最近見た動画
            histories = History.objects.filter(user=request.user.id).exclude(target__user__blocked=request.user.id).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

            hist_id_list   = []
            for history in histories:
                hist_id_list.append(history.target.id)

            histories = Video.objects.annotate(num_comments=Count("videocomment", distinct=True),num_mylists=Count("mylist", distinct=True)).filter(id__in=hist_id_list).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

            # フォローユーザーの動画
            follows = Video.objects.filter(user__followed=request.user.id).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]
            follows = Video.objects.annotate(num_comments=Count("videocomment", distinct=True),num_mylists=Count("mylist", distinct=True)).filter(user__followed=request.user.id).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

            # 新着順(ブロックしたユーザーは除外)
            latests = Video.objects.exclude(user__blocked=request.user.id).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

            latests = Video.objects.annotate(num_comments=Count("videocomment", distinct=True),num_mylists=Count("mylist", distinct=True)).exclude(user__blocked=request.user.id).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]
            # これで動画一覧表示時に、マイリス数とコメント数をセットで表示できる。

        else:
            histories = False
            follows = False

        context = {"latests": latests,
                   "histories": histories,
                   "follows": follows,
                   }

        return render(request, "tube/index.html", context)

index = IndexView.as_view()

#アップロードページ
class UploadView(LoginRequiredMixin,views.APIView):

    def get(self,request, *args, **kwargs):

        categories = Category.objects.all()
        context = {"categories": categories}

        return render(request, "tube/upload.html", context)


    def post(self, request, *args, **kwargs):

        print(request.data)

        request.data["user"]    = request.user.id
        serializer              = VideoSerializer(data=request.data)
        mime_type               = magic.from_buffer(request.FILES["movie"].read(1024), mime=True)

        print(request.data["movie"].size)
        print(type(request.data["movie"].size))

        if request.FILES["movie"].size >= LIMIT_SIZE:
            mb = str(LIMIT_SIZE / 1000000)

            json = {"error": True,
                    "message": "The maximum file size is " + mb + "MB"}

            return JsonResponse(json)

        if mime_type not in ALLOWED_MIME:
            mime = str(ALLOWED_MIME)
            json = {"error": True,
                    "message": "The file you can post is " + mime + "."}

            return JsonResponse(json)

        if serializer.is_valid():
            serializer.save()
        else:
            json    = { "error":True,
                        "message":"入力内容に誤りがあります。" }
            return JsonResponse(json)

        json    = { "error":False,
                    "message":"アップロード完了しました。" }

        return JsonResponse(json)


upload = UploadView.as_view()



#検索結果表示ページ
class SearchView(views.APIView):

    def get(self, request, *args, **kwargs):

        query = Q()
        page = 1

        if "word" in request.GET:

            word_list = request.GET["word"].replace("　", " ").split(" ")
            for w in word_list:
                query &= Q(Q(title__icontains=w) | Q(description__icontains=w))

        if "page" in request.GET:
            page = request.GET["page"]

        # TODO:ここでログインしていれば、ブロックユーザーを除外した検索をする。
        if request.user.is_authenticated:
            videos = Video.objects.filter(query).exclude(user__blocked=request.user.id).order_by("-dt")

            videos = Video.objects.filter(query).annotate(num_comments=Count("videocomment", distinct=True),num_mylists=Count("mylist", distinct=True)).exclude(user__blocked=request.user.id).order_by("-dt")

        else:
            videos = Video.objects.filter(query).order_by("-dt")

        amount = len(videos)

        videos_paginator = Paginator(videos, SEARCH_AMOUNT_PAGE)
        videos           = videos_paginator.get_page(page)

        context = {"videos": videos,
                   "amount": amount}

        return render(request, "tube/search.html", context)

search = SearchView.as_view()


#動画個別ページ
class SingleView(views.APIView):

    def get(self,request, video_pk,*args, **kwargs):

        print(request.user.username)

        video = Video.objects.filter(id=video_pk).first()

        blockeduser = CustomUser.objects.filter(blocked=video.user.id)
        print(blockeduser)

        if request.user in blockeduser:
            print("ブロックされています")
            return redirect( "tube:index" )
        else:
            print("ブロックされていません")

        #Todo:F5で再生回数水増し可能。
        video.views = video.views + 1
        video.save()

        if request.user.is_authenticated:
            print("認証済みユーザーです")

            history = History.objects.filter(user=request.user.id, target=video_pk).first()

            if history:
                print("存在する場合の処理")
                history.views   = history.views + 1
                history.dt      = timezone.now()
                history.save()
            else:
                print("履歴に存在しない場合の処理")
                data        = { "target":video_pk,
                                "user":request.user.id,}
                serializer  = HistorySerializer(data=data)

                if serializer.is_valid():
                    serializer.save()


        img   = qrcode.make(request.build_absolute_uri()) #動画のQRコード
        buffer = BytesIO()
        img.save(buffer, format="PNG")
        qr = base64.b64encode(buffer.getvalue()).decode().replace("'", "")

        counts = Video.objects.annotate(num_comments=Count("videocomment", distinct=True),num_mylists=Count("mylist", distinct=True)).filter(id=video_pk).first()

        comments = VideoComment.objects.filter(target=video_pk).order_by("-dt")
        comments = VideoComment.objects.annotate(num_reply=Count("videocommentreply", distinct=True)).filter(target=video_pk).order_by("-dt")

        good        = GoodVideo.objects.filter(target=video_pk)
        already_good    = GoodVideo.objects.filter(target=video_pk, user=request.user.id)

        relates         = Video.objects.filter(category=video.category).prefetch_related('category').order_by("-dt")

        mylist          = MyList.objects.filter(target=video_pk)
        already_mylist  = MyList.objects.filter(target=video_pk, user=request.user.id)

        categories      = Category.objects.all()

        paginator = Paginator(comments, 10)
        comments = paginator.get_page(1)

        context = {"video": video,
                   "comments": comments,
                   "good": good,
                   "already_good": already_good,
                   "mylist":mylist,
                   "already_mylist":already_mylist,
                   "relates": relates,
                   "qr":qr,
                   "counts":counts,
                   "categories":categories,
                   }

        return render(request, "tube/single/single.html", context)


single = SingleView.as_view()


class SingleModView(LoginRequiredMixin,views.APIView):

    #ここでコメントのページネーション↑ のクラス名変えるべきでは？
    def get(self,request,video_pk,*args,**kwargs):

        page        = 1
        if "page" in request.GET:
            page    = request.GET["page"]

        video               = Video.objects.filter(id=video_pk).first()
        comments            = VideoComment.objects.filter(target=video_pk).order_by("-dt")
        comments            = VideoComment.objects.annotate(num_reply=Count("videocommentreply", distinct=True)).filter(target=video_pk).order_by("-dt")

        comments_paginator  = Paginator(comments,COMMENTS_AMOUNT_PAGE)
        comments            = comments_paginator.get_page(page)




templates/tube/mypage/mypage.html
{% extends "tube/mypage_base.html" %}
{% load humanize %}
{% load static %}

{% block extra_head %}
{{ block.super }}

<script src="{% static 'tube/js/usericon.js' %}"></script>
<script src="{% static 'tube/js/information_update.js' %}"></script>
{% endblock %}

{% block mypage_content %}



    <h2>基本情報</h2>

    <table>
        {% if custom_user.usericon %}
        <tr id="mypage_usericon_area">
            {% include "tube/mypage/mypage_usericon.html" %}
        </tr>
        {% endif %}
    </table>

    <table class="mypage_introduction_area">
        <tr>
            <td>ユーザー名</td>
            <td>{{ custom_user.username }}</td>
        </tr>
        <tr>
            <td>ハンドルネーム</td>
            <td>{{ custom_user.handle_name }}</td>
        </tr>
        <tr>
            <td>最終ログイン</td>
            <td>{{ custom_user.last_login }}</td>
        </tr>
        <tr>
            <td>メールアドレス</td>
            <td>{{ custom_user.email }}</td>
        </tr>
        <tr>
            <td>自己紹介</td>
            <td>{{ custom_user.self_introduction|linebreaksbr|urlize }}</td>
        </tr>
    </table></br>

    <input id="icon_tab1" class="icon_tab_radio" type="checkbox" name="icon_tab"><label for="icon_tab1" class="icon_tab_label">アイコン登録/変更</label>
    <input id="icon_tab2" class="icon_tab_radio" type="checkbox" name="icon_tab"><label for="icon_tab2" class="icon_tab_label">基本情報登録/変更</label>


    <div id="iconupload_hide_area">
        <div class="user-icon-dnd-wrapper">
            <input id="icon_upload1" type="file" name="usericon" accept=".jpg,.png">
            <div id="drop_area">drag and drop<br>or<br>click here.</div>
        </div>

        <form id="icon_upload_form" name="icon_upload_form" method="POST" action="{% url 'tube:mypage' %}" enctype="multipart/form-data">
        {% csrf_token %}
            <div class="icon_canvas">
                <div id="icon_clear_button"><i class="far fa-times-circle"></i></div>
                <input id='scal' class="scaling" type='range' value='' min='5' max='400'><br>
                <canvas id='cvs' width='300' height='300'></canvas><br>
                <input id="icon_upload2" class="btn-gradient-radius" type="button" value="送信">
            </div>
        </form>
    </div>
    <div id="upload_message" class="upload_message"></div>

    <div class="information_update_area">
        <form id="information_update_form" action="{% url 'tube:useredit' request.user.id %}" >
            {% csrf_token %}
            <input class="input_form_text" type="text" value="{{ request.user.handle_name }}" name="handle_name" placeholder="ハンドルネーム">
            <textarea class="textarea_form" name="self_introduction" rows="4" placeholder="自己紹介">{{ request.user.self_introduction }} </textarea>
            <input id="information_update" class="btn-gradient-success" type="button" value="編集">
        </form>
    </div>

    <div id="delete_message" class="js_message"></div>

    <h2>投稿した動画</h2>

    <div class="video_content_list">
        {% for video in videos %}
        <div class="mypage_video_content">
            <a class="video_content_link" href="{% url 'tube:single' video.id %}">
                {% if video.thumbnail %}
                <img class="mypage_thumbnail" src="{{ video.thumbnail.url }}" alt="{{ video.title }}">
                {% else %}
                <img class="mypage_thumbnail" src="{% static 'tube/img/no-img.png' %}" alt="{{ video.title }}">
                {% endif %}
            </a>

            <div class="index_video_content_inner">
                <div class="index_video_content_inner_left">
                    {% if video.user.usericon %}
                    <a href="{% url 'tube:usersingle' video.user.id %}"><img class="index_usericon" src="{{ video.user.usericon.url }}" alt="icon"></a>
                    {% else %}
                    <!--TODO:要修正-->
                    <a href="{% url 'tube:usersingle' video.user.id %}"><img class="index_usericon" src="/media/tube/usericon/non_usericon.png" alt="{{ icon }}"></a>
                    {% endif %}
                </div>

                <div class="index_video_content_inner_right">
                    <a href="{% url 'tube:single' video.id %}"><div class="video_title">{{ video.title }}</div></a>
                    <a href="{% url 'tube:usersingle' video.user.id %}"><div>{{ video.user.handle_name }} </div></a>

                    <div class="video_value">
                        <span class="v_value_span"><i class="far fa-play-circle"></i>{{ video.views|intcomma }}</span>
                        <span class="v_value_span"><i class="far fa-comments"></i>{{ video.num_comments }}</span>
                        <span class="v_value_span"><i class="far fa-list-alt"></i>{{ video.num_mylists }}</span>
                    </div>
                    <div>{{ video.dt|date:"Y年m月d日 H時i分s秒" }}</div>
                    <div>{{ video.category }}</div>
                </div>
            </div>


        </div>
        {% empty %}
        <div class="mypage_video_content"><p>投稿した動画はありません。<a href="{% url 'tube:upload' %}">アップロード</a>から投稿できます。</p></div>
        {% endfor %}
    </div>
    
    <h2>高く評価した動画</h2>

    <div class="video_content_list">
        {% for video in good_videos %}
        <div class="mypage_video_content">
            <a class="video_content_link" href="{% url 'tube:single' video.id %}">
                {% if video.thumbnail %}
                <img class="mypage_thumbnail" src="{{ video.thumbnail.url }}" alt="{{ video.title }}">
                {% else %}
                <img class="mypage_thumbnail" src="{% static 'tube/img/no-img.png' %}" alt="{{ video.title }}">
                {% endif %}
            </a>


            <div class="index_video_content_inner">
                <div class="index_video_content_inner_left">
                    {% if video.user.usericon %}
                    <a href="{% url 'tube:usersingle' video.user.id %}"><img class="index_usericon" src="{{ video.user.usericon.url }}" alt="icon"></a>
                    {% else %}
                    <a href="{% url 'tube:usersingle' video.user.id %}"><img class="index_usericon" src="/media/tube/usericon/non_usericon.png" alt="{{ icon }}"></a>
                    {% endif %}
                </div>

                <div class="index_video_content_inner_right">
                    <a href="{% url 'tube:single' video.id %}"><div class="video_title">{{ video.title }}</div></a>
                    <a href="{% url 'tube:usersingle' video.user.id %}"><div>{{ video.user.handle_name }} </div></a>

                    <div class="video_value">
                        <span class="v_value_span"><i class="far fa-play-circle"></i>{{ video.views|intcomma }}</span>
                        <span class="v_value_span"><i class="far fa-comments"></i>{{ video.num_comments }}</span>
                        <span class="v_value_span"><i class="far fa-list-alt"></i>{{ video.num_mylists }}</span>
                    </div>
                    <div>{{ video.dt|date:"Y年m月d日 H時i分s秒" }}</div>
                    <div>{{ video.category }}</div>
                </div>
            </div>

        </div>
        {% empty %}
        <div class="video_content"><p>高評価した動画はありません。</div>
        {% endfor %}
    </div>



{% endblock %}

templates/tube/mypage/mypage_usericon.html
<td><img class="mypage_usericon" src="{{ custom_user.usericon.url }}" alt="icon"></td>