config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("tube.urls")),
    path('users', include("users.urls")),
    path('accounts/',include("allauth.urls")),# ←allauthのurls.pyを登録
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tube/urls.py
from django.urls import path
from . import views


app_name = "tube"
urlpatterns =[
    path('', views.index, name="index"),

    path('search/', views.search, name="search"),

    # TIPS:<型:変数名>とすることでビューに変数を与えることができる
    #idをuuidにするので、intをuuidに変える。

    path('single/<uuid:video_pk>/', views.single, name="single"),
    path('single_mod/<uuid:video_pk>/', views.single_mod, name="single_mod"),
    path('video_comment_reply/<uuid:comment_pk>/', views.video_comment_reply, name="video_comment_reply"),
    path('video_comment_reply_to_reply/<uuid:videocommentreply_pk>/', views.video_comment_reply_to_reply, name="video_comment_reply_to_reply"),
    path('video_comment_edit/<uuid:comment_pk>/', views.video_comment_edit, name="video_comment_edit"),
    path('video_comment_reply_edit/<uuid:reply_pk>/', views.video_comment_reply_edit, name="video_comment_reply_edit"),

    ##ランキングページ。DBからデータ抜き取って表示するだけ。GET文だけ
    path('rank/', views.rank, name="rank"),
    path('user_policy', views.user_policy, name="user_policy"),

    # 以下認証済みユーザー専用
    path('mypage/', views.mypage, name="mypage"),
    path('history/', views.history, name="history"),
    path('recommend/', views.recommend, name="recommend"),
    path('notify/', views.notify, name="notify"),
    path('mylist/', views.mylist, name="mylist"),
    path('upload', views.upload, name="upload"),
    path('config/', views.config, name="config"),


    path('usersingle/<uuid:pk>/', views.usersingle, name="usersingle"),
    path('userfollow/<uuid:pk>/', views.userfollow, name="userfollow"),
    path('userblock/<uuid:pk>/', views.userblock, name="userblock"),
    path('useredit/<uuid:pk>/', views.useredit, name="useredit"),
]

tube/views.py
from rest_framework import status,views,response

from django.shortcuts import render, redirect

from django.db.models import Q,Count

from django.http.response import JsonResponse

from django.template.loader import render_to_string

from django.core.paginator import Paginator

from django.conf import settings

#TIPS:ログイン状態かチェックする。ビュークラスに継承元として指定する(多重継承なので順番に注意)。未ログインであればログインページへリダイレクト。
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone

from .models import Video,Category,VideoComment,VideoCommentReply,VideoCommentReplyToReply,MyList,History,GoodVideo

from users.models import CustomUser,FollowUser,BlockUser

from .serializer import VideoSerializer,VideoEditSerializer,VideoCommentSerializer,VideoCommentEditSerializer,VideoCommentReplyEditSerializer,VideoCommentReplySerializer,VideoCommentReplyToReplySerializer,MyListSerializer,HistorySerializer,RateSerializer,GoodSerializer,IconSerializer,FollowUserSerializer,BlockUserSerializer,UserInformationSerializer

DEFAULT_VIDEO_AMOUNT = 10
COMMENTS_AMOUNT_PAGE = 10

#python-magicで受け取ったファイルのMIMEをチェックする。
#MIMEについては https://developer.mozilla.org/ja/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types を参照。

from PIL import Image
import qrcode
from io import BytesIO
import base64

import magic
ALLOWED_MIME   = ["video/mp4"]

# アップロードの上限
LIMIT_SIZE     = 200 * 1000 * 1000

SEARCH_AMOUNT_PAGE  = 20

#トップページ
class IndexView(views.APIView):

    def get(self, request,*args, **kwargs):

        # 新着順
        latests = Video.objects.all().order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]
        latests = Video.objects.annotate(num_comments=Count("videocomment", distinct=True),num_mylists=Count("mylist", distinct=True)).all().order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

        if request.user.is_authenticated:

            # 最近見た動画
            histories = History.objects.filter(user=request.user.id).exclude(target__user__blocked=request.user.id).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

            hist_id_list   = []
            for history in histories:
                hist_id_list.append(history.target.id)

            histories = Video.objects.annotate(num_comments=Count("videocomment", distinct=True),num_mylists=Count("mylist", distinct=True)).filter(id__in=hist_id_list).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

            # フォローユーザーの動画
            follows = Video.objects.filter(user__followed=request.user.id).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]
            follows = Video.objects.annotate(num_comments=Count("videocomment", distinct=True),num_mylists=Count("mylist", distinct=True)).filter(user__followed=request.user.id).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

            # 新着順(ブロックしたユーザーは除外)
            latests = Video.objects.exclude(user__blocked=request.user.id).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

            latests = Video.objects.annotate(num_comments=Count("videocomment", distinct=True),num_mylists=Count("mylist", distinct=True)).exclude(user__blocked=request.user.id).order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]
            # これで動画一覧表示時に、マイリス数とコメント数をセットで表示できる。

        else:
            histories = False
            follows = False

        context = {"latests": latests,
                   "histories": histories,
                   "follows": follows,
                   }

        return render(request, "tube/index.html", context)

index = IndexView.as_view()

#アップロードページ
class UploadView(LoginRequiredMixin,views.APIView):

    def get(self,request, *args, **kwargs):

        categories = Category.objects.all()
        context = {"categories": categories}

        return render(request, "tube/upload.html", context)


    def post(self, request, *args, **kwargs):

        print(request.data)

        request.data["user"]    = request.user.id
        serializer              = VideoSerializer(data=request.data)
        mime_type               = magic.from_buffer(request.FILES["movie"].read(1024), mime=True)

        print(request.data["movie"].size)
        print(type(request.data["movie"].size))

        if request.FILES["movie"].size >= LIMIT_SIZE:
            mb = str(LIMIT_SIZE / 1000000)

            json = {"error": True,
                    "message": "The maximum file size is " + mb + "MB"}

            return JsonResponse(json)

        if mime_type not in ALLOWED_MIME:
            mime = str(ALLOWED_MIME)
            json = {"error": True,
                    "message": "The file you can post is " + mime + "."}

            return JsonResponse(json)

        if serializer.is_valid():
            serializer.save()
        else:
            json    = { "error":True,
                        "message":"入力内容に誤りがあります。" }
            return JsonResponse(json)

        json    = { "error":False,
                    "message":"アップロード完了しました。" }

        return JsonResponse(json)


upload = UploadView.as_view()



#検索結果表示ページ
class SearchView(views.APIView):

    def get(self, request, *args, **kwargs):

        query = Q()
        page = 1

        if "word" in request.GET:

            word_list = request.GET["word"].replace("　", " ").split(" ")
            for w in word_list:
                query &= Q(Q(title__icontains=w) | Q(description__icontains=w))

        if "page" in request.GET:
            page = request.GET["page"]

        # TODO:ここでログインしていれば、ブロックユーザーを除外した検索をする。
        if request.user.is_authenticated:
            videos = Video.objects.filter(query).exclude(user__blocked=request.user.id).order_by("-dt")

            videos = Video.objects.filter(query).annotate(num_comments=Count("videocomment", distinct=True),num_mylists=Count("mylist", distinct=True)).exclude(user__blocked=request.user.id).order_by("-dt")

        else:
            videos = Video.objects.filter(query).order_by("-dt")

        amount = len(videos)

        videos_paginator = Paginator(videos, SEARCH_AMOUNT_PAGE)
        videos           = videos_paginator.get_page(page)

        context = {"videos": videos,
                   "amount": amount}

        return render(request, "tube/search.html", context)

search = SearchView.as_view()


#動画個別ページ
class SingleView(views.APIView):

    def get(self,request, video_pk,*args, **kwargs):

        print(request.user.username)

        video = Video.objects.filter(id=video_pk).first()

        blockeduser = CustomUser.objects.filter(blocked=video.user.id)
        print(blockeduser)

        if request.user in blockeduser:
            print("ブロックされています")
            return redirect( "tube:index" )
        else:
            print("ブロックされていません")

        #Todo:F5で再生回数水増し可能。
        video.views = video.views + 1
        video.save()

        if request.user.is_authenticated:
            print("認証済みユーザーです")

            history = History.objects.filter(user=request.user.id, target=video_pk).first()

            if history:
                print("存在する場合の処理")
                history.views   = history.views + 1
                history.dt      = timezone.now()
                history.save()
            else:
                print("履歴に存在しない場合の処理")
                data        = { "target":video_pk,
                                "user":request.user.id,}
                serializer  = HistorySerializer(data=data)

                if serializer.is_valid():
                    serializer.save()


        img   = qrcode.make(request.build_absolute_uri()) #動画のQRコード
        buffer = BytesIO()
        img.save(buffer, format="PNG")
        qr = base64.b64encode(buffer.getvalue()).decode().replace("'", "")

        counts = Video.objects.annotate(num_comments=Count("videocomment", distinct=True),num_mylists=Count("mylist", distinct=True)).filter(id=video_pk).first()

        comments = VideoComment.objects.filter(target=video_pk).order_by("-dt")
        comments = VideoComment.objects.annotate(num_reply=Count("videocommentreply", distinct=True)).filter(target=video_pk).order_by("-dt")

        good        = GoodVideo.objects.filter(target=video_pk)
        already_good    = GoodVideo.objects.filter(target=video_pk, user=request.user.id)

        relates         = Video.objects.filter(category=video.category).prefetch_related('category').order_by("-dt")

        mylist          = MyList.objects.filter(target=video_pk)
        already_mylist  = MyList.objects.filter(target=video_pk, user=request.user.id)

        categories      = Category.objects.all()

        paginator = Paginator(comments, 10)
        comments = paginator.get_page(1)

        context = {"video": video,
                   "comments": comments,
                   "good": good,
                   "already_good": already_good,
                   "mylist":mylist,
                   "already_mylist":already_mylist,
                   "relates": relates,
                   "qr":qr,
                   "counts":counts,
                   "categories":categories,
                   }

        return render(request, "tube/single/single.html", context)


single = SingleView.as_view()


class SingleModView(LoginRequiredMixin,views.APIView):

    #ここでコメントのページネーション↑ のクラス名変えるべきでは？
    def get(self,request,video_pk,*args,**kwargs):

        page        = 1
        if "page" in request.GET:
            page    = request.GET["page"]

        video               = Video.objects.filter(id=video_pk).first()
        comments            = VideoComment.objects.filter(target=video_pk).order_by("-dt")
        comments            = VideoComment.objects.annotate(num_reply=Count("videocommentreply", distinct=True)).filter(target=video_pk).order_by("-dt")

        comments_paginator  = Paginator(comments,COMMENTS_AMOUNT_PAGE)
        comments            = comments_paginator.get_page(page)




templates/tube/base.html
{% extends "common/sidebar.html" %}
{% load static %}

{% block page_title %}{% endblock %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'tube/css/style.css' %}">

<script src="{% static 'common/js/ajax.js' %}"></script>
{% endblock %}

{% block header_title %}TubeIntegrity{% endblock %}

{% block header_right_content %}
    {% if request.user.is_authenticated %}
        <a class="header_icon" href="{% url 'tube:notify' %}" aria-label="notify">
            <i class="far fa-bell"></i>
        </a>
        {% if request.user.usericon %}
        <a href="{% url 'tube:mypage' %}" aria-label="mypage">
            <img class="usericon" src="{{ request.user.usericon.url }}" alt="icon">
        </a>
        {% else %}
        <a class="header_icon" href="{% url 'tube:mypage' %}" aria-label="mypage">
            <i class="fas fa-user"></i>
        </a>
        {% endif %}

    {% else %}
        <a class="header_icon" href="{% url 'account_signup' %}" aria-label="signup">
            <i class="fas fa-user-plus"></i>
        </a>
        <a class="header_icon" href="{% url 'account_login' %}" aria-label="login">
            <i class="fas fa-sign-in-alt"></i>
        </a>
    {% endif %}
{% endblock %}

{% block sidebar_content %}
<div class="sidebar_content_area">

    <div class="sidebar_content">
		<a href="{% url 'tube:rank' %}" class="sidebar_icon"><i class="fas fa-crown"></i><div class="sidebar_explain">ランキング</div></a>
	</div>
    <div class="sidebar_content">
		<a href="{% url 'tube:search' %}" class="sidebar_icon"><i class="far fa-lightbulb"></i><div class="sidebar_explain">新着動画</div></a>
	</div>

    {% if request.user.is_authenticated %}
    <!-- 認証済みユーザーのアイコン-->
    <div class="sidebar_content">
		<a href="{% url 'tube:mypage' %}" class="sidebar_icon"><i class="fas fa-user"></i><div class="sidebar_explain">マイページ</div></a>
	</div>
    <div class="sidebar_content">
		<a href="{% url 'tube:notify' %}" class="sidebar_icon"><i class="far fa-bell"></i><div class="sidebar_explain">通知</div></a>
	</div>
    <div class="sidebar_content">
		<a href="{% url 'tube:history' %}" class="sidebar_icon"><i class="fas fa-history"></i><div class="sidebar_explain">視聴履歴</div></a>
	</div>
    <div class="sidebar_content">
		<a href="{% url 'tube:mylist' %}" class="sidebar_icon"><i class="far fa-list-alt"></i><div class="sidebar_explain">マイリスト</div></a>
	</div>
    <div class="sidebar_content">
		<a href="{% url 'tube:recommend' %}" class="sidebar_icon"><i class="far fa-star"></i><div class="sidebar_explain">おすすめ</div></a>
	</div>
    <div class="sidebar_content">
		<a href="{% url 'tube:upload' %}" class="sidebar_icon"><i class="far fa-file-video"></i><div class="sidebar_explain">アップロード</div></a>
	</div>
    <div class="sidebar_content">
		<a href="{% url 'tube:config' %}" class="sidebar_icon"><i class="fas fa-cogs"></i><div class="sidebar_explain">設定</div></a>
	</div>
    <div class="sidebar_content">
		<a href="{% url 'account_logout' %}" class="sidebar_icon"><i class="fas fa-sign-out-alt"></i><div class="sidebar_explain">ログアウト</div></a>
	</div>
    {% else %}
    <!-- 未認証ユーザーのアイコン-->
    <div class="sidebar_content">
		<a href="{% url 'account_signup' %}" class="sidebar_icon"><i class="fas fa-user-plus"></i><div class="sidebar_explain">会員登録</div></a>
	</div>
    <div class="sidebar_content">
		<a href="{% url 'account_login' %}" class="sidebar_icon"><i class="fas fa-sign-in-alt"></i><div class="sidebar_explain">ログイン</div></a>
	</div>
    {% endif %}


    <div class="sidebar_content">
		<a href="" class="sidebar_icon"><i class="far fa-question-circle"></i><div class="sidebar_explain">ヘルプ</div></a>
	</div>
    <div class="sidebar_content">
		<a href="{% url 'tube:user_policy' %}" class="sidebar_icon"><i class="fas fa-book"></i><div class="sidebar_explain">利用規約</div></a>
	</div>

</div>
{% endblock %}

{% block main %}
{% endblock %}


templates/tube/config.html
{% extends "tube/mypage_base.html" %}
{% load static %}


{% block mypage_content %}

<h2>設定</h2>

    {# {% include "tube/follow.html" %} #}

    <h3>フォロー中ユーザー</h3>
    {% for follow_user in follow_users %}
    <div>
        {% if follow_user.to_user.usericon %}
        <a href="{% url 'tube:usersingle' follow_user.to_user.id  %}"><img class="usericon" src="{{ follow_user.to_user.usericon.url }}" alt="icon"></a>
        {% else %}
        <a href="{% url 'tube:usersingle' follow_user.to_user.id  %}"><img class="usericon" src="{% static 'tube/img/non_usericon.png' %}" alt="{{ icon }}"></a>
        {% endif %}
        <a href="{% url 'tube:usersingle' follow_user.to_user.id  %}">{{ follow_user.to_user.handle_name }}</a>
    </div>
    {% endfor%}

    <h3>フォロワーユーザー</h3>
    {% for follow_user in follower_users %}
    <div>
        {% if follow_user.from_user.usericon %}
        <a href="{% url 'tube:usersingle' follow_user.from_user.id  %}"><img class="usericon" src="{{ follow_user.from_user.usericon.url }}" alt="icon"></a>
        {% else %}
        <a href="{% url 'tube:usersingle' follow_user.from_user.id  %}"><img class="usericon" src="{% static 'tube/img/non_usericon.png' %}" alt="{{ icon }}"></a>
        {% endif %}
        <a href="{% url 'tube:usersingle' follow_user.from_user.id  %}">{{ follow_user.from_user.handle_name }}</a>
    </div>
    {% endfor%}

    <h3>ブロック中ユーザー</h3>
    {# blockを変数名にしてしまうとシンタックスカラーなどで問題あり(テンプレートタグのblockと解釈される)のため、block_userとする #}
    {% for block_user in block_users %}
    <div>
        {% if block_user.to_user.usericon %}
        <a href="{% url 'tube:usersingle' block_user.to_user.id  %}"><img class="usericon" src="{{ block_user.to_user.usericon.url }}" alt="icon"></a>
        {% else %}
        <a href="{% url 'tube:usersingle' block_user.to_user.id  %}"><img class="usericon" src="{% static 'tube/img/non_usericon.png' %}" alt="{{ icon }}"></a>
        {% endif %}
        <a href="{% url 'tube:usersingle' block_user.to_user.id  %}">{{ block_user.to_user.handle_name }}</a>
    </div>
    {% endfor%}

<!--ユーザーモデルに設定欄を追加させる-->


{% endblock %}

templates/tube/mypage_base.html
{% extends "tube/base.html" %}
{% load static %}

{% block main %}

{% include "tube/search_form.html" %}


<div class="mypage_content_area">

    <div class="mypage_menu">

        <!--このチェックボックス表示化の機構はスマホ表示時のみ有効とする。-->
        <input id="mypage_menu_chk" class="mypage_menu_chk" type="checkbox">
        <label for="mypage_menu_chk" class="mypage_menu_label">マイページメニュー</label>
        
        <div class="mypage_menu_area">

            <div class="menu_content">
                <a href="{% url 'tube:mypage' %}" class="menu_icon"><i class="fas fa-user"></i><div class="menu_explain">マイページ</div></a>
            </div>
            <div class="menu_content">
                <a href="{% url 'tube:notify' %}" class="menu_icon"><i class="far fa-bell"></i><div class="menu_explain">通知</div></a>
            </div>
            <div class="menu_content">
                <a href="{% url 'tube:history' %}" class="menu_icon"><i class="fas fa-history"></i><div class="menu_explain">視聴履歴</div></a>
            </div>
            <div class="menu_content">
                <a href="{% url 'tube:mylist' %}" class="menu_icon"><i class="far fa-list-alt"></i><div class="menu_explain">マイリスト</div></a>
            </div>
            <div class="menu_content">
                <a href="{% url 'tube:recommend' %}" class="menu_icon"><i class="far fa-star"></i><div class="menu_explain">おすすめ</div></a>
            </div>
            <div class="menu_content">
                <a href="{% url 'tube:upload' %}" class="menu_icon"><i class="far fa-file-video"></i><div class="menu_explain">アップロード</div></a>
            </div>
            <div class="menu_content">
                <a href="{% url 'tube:config' %}" class="menu_icon"><i class="fas fa-cogs"></i><div class="menu_explain">設定</div></a>
            </div>
            <div class="menu_content">
                <a href="{% url 'account_logout' %}" class="menu_icon"><i class="fas fa-sign-out-alt"></i><div class="menu_explain">ログアウト</div></a>
            </div>

        </div>

    </div>

    <div class="mypage_content">
        <div class="mypage_content_body">
            {% block mypage_content %}{% endblock %}
        </div>
    </div>

</div>











{% endblock %}


templates/tube/rank.html
{% extends "tube/base.html" %}
{% load static %}

{% block main %}

{% include "tube/search_form.html" %}

    ランキングページ

    {% for video in videos %}
    <div class="single_video_area">
        <p>{{ video.title }}</p>
        <p>{{ video.description }}</p>
        <a href="{% url 'tube:single' video.id %}">見る</a>
    </div>
    {% endfor %}

{% endblock %}



templates/tube/usersingle.html
{% extends "tube/mypage_base.html" %}
{% load static %}
{% load humanize %}


{% block extra_head %}
{{ block.super }}
<script src="{% static 'tube/js/single.js' %}"></script>
{% endblock %}


{% block mypage_content %}


    {% if user %}
    <div>
        <h2>{{ user.handle_name }}</h2>

        <div>
            {% if user.usericon %}
            <img class="video_usericon" src="{{ user.usericon.url }}" alt="icon">
            {% else %}
            <img class="video_usericon" src="{% static 'tube/img/non_usericon.png' %}" alt="{{ icon }}">
            {% endif %}

            <div>{{ user.self_introduction|linebreaksbr|urlize }}</div>
            <div>{{ user.date_joined|date:"Y年m月d日 H時i分s秒" }}に登録</div>
        </div>

        {% if request.user.is_authenticated and request.user.id != user.id %}  {# 自分自身であればボタンを表示させない#}
        <div style="margin:0.5rem 0;">
            <form id="follow_user_form" action="{% url 'tube:userfollow' user.id  %}" method="POST" style="display:inline-block;">
                {% if request.user in user.followed.all %}
                <button class="follow btn btn-primary" type="button">フォロー中</button>
                {% else %}
                <button class="follow btn btn-outline-primary" type="button">フォローする</button>
                {% endif %}
            </form>
            <form id="block_user_form" action="{% url 'tube:userblock' user.id  %}" method="POST" style="display:inline-block;">
                {% if request.user in user.blocked.all %}
                <button class="block btn btn-danger" type="button">ブロック中</button>
                {% else %}
                <button class="block btn btn-outline-danger" type="button">ブロックする</button>
                {% endif %}
            </form>
        </div>
        {% endif %}
        
        <!--ここでタブシステムを使う。
            スマホ表示時、普通のタブシステムだと折り返されるので、overflow-xとwhite-space:nowrapを組み合わせ、横スクロール形式に仕立てる。
            ラジオチェック時にラベルを装飾する際に指定するセレクタも変わるので、それに合わせる。-->

        <input id="user_single_detail_radio_1" class="user_single_detail_radio" type="radio" name="user_single_detail_radio" checked>
        <input id="user_single_detail_radio_2" class="user_single_detail_radio" type="radio" name="user_single_detail_radio">
        <input id="user_single_detail_radio_3" class="user_single_detail_radio" type="radio" name="user_single_detail_radio">
        <input id="user_single_detail_radio_4" class="user_single_detail_radio" type="radio" name="user_single_detail_radio">

        <div class="user_single_detail_label_area">
            <label class="user_single_detail_label" for="user_single_detail_radio_1">フォロー中</label>
            <label class="user_single_detail_label" for="user_single_detail_radio_2">フォロワー</label>
            <label class="user_single_detail_label" for="user_single_detail_radio_3">ブロック中</label>
            <label class="user_single_detail_label" for="user_single_detail_radio_4">投稿した動画</label>
        </div>

        <!--ここは別テンプレート化したほうがわかりやすいかも知れない。-->
        <div id="user_single_detail_area_1" class="user_single_detail_area">
        
            <h3>フォロー中</h3>
            {% for follow_user in follow_users %}
            <div>
                {% if follow_user.to_user.usericon %}
                <a href="{% url 'tube:usersingle' follow_user.to_user.id  %}"><img class="video_usericon" src="{{ follow_user.to_user.usericon.url }}" alt="icon"></a>
                {% else %}
                <a href="{% url 'tube:usersingle' follow_user.to_user.id  %}"><img class="video_usericon" src="{% static 'tube/img/non_usericon.png' %}" alt="{{ icon }}"></a>
                {% endif %}
                <a href="{% url 'tube:usersingle' follow_user.to_user.id  %}">{{ follow_user.to_user.handle_name }}</a>
            </div>
            {% endfor%}
            
        </div>
        <div id="user_single_detail_area_2" class="user_single_detail_area">
            <h3>フォロワー</h3>
            {% for follow_user in follower_users %}
            <div>
                {% if follow_user.from_user.usericon %}
                <a href="{% url 'tube:usersingle' follow_user.from_user.id  %}"><img class="video_usericon" src="{{ follow_user.from_user.usericon.url }}" alt="icon"></a>
                {% else %}
                <a href="{% url 'tube:usersingle' follow_user.from_user.id  %}"><img class="video_usericon" src="{% static 'tube/img/non_usericon.png' %}" alt="{{ icon }}"></a>
                {% endif %}
                <a href="{% url 'tube:usersingle' follow_user.from_user.id  %}">{{ follow_user.from_user.handle_name }}</a>
            </div>
            {% endfor%}
        
        
        </div>
        <div id="user_single_detail_area_3" class="user_single_detail_area">

            {# ここから先、投稿者自身usersingle #}
            {% if request.user.is_authenticated and request.user.id == user.id %}

            <h3>ブロック中</h3>
            {# blockを変数名にしてしまうとシンタックスカラーなどで問題あり(テンプレートタグのblockと解釈される)のため、block_userとする #}
            {% for block_user in block_users %}
            <div>
                {% if block_user.to_user.usericon %}
                <a href="{% url 'tube:usersingle' block_user.to_user.id  %}"><img class="video_usericon" src="{{ block_user.to_user.usericon.url }}" alt="icon"></a>
                {% else %}
                <a href="{% url 'tube:usersingle' block_user.to_user.id  %}"><img class="video_usericon" src="{% static 'tube/img/non_usericon.png' %}" alt="{{ icon }}"></a>
                {% endif %}
                <a href="{% url 'tube:usersingle' block_user.to_user.id  %}">{{ block_user.to_user.handle_name }}</a>
            </div>
            {% endfor%}

            {% endif %}
            {# ここまで、投稿者自身のusersingle #}
        
        
        </div>
        <div id="user_single_detail_area_4" class="user_single_detail_area">
        
            <h3>投稿動画</h3>

            <div class="video_content_list">
                {% for video in videos %}
                <div class="mypage_video_content">
                    <a class="video_content_link" href="{% url 'tube:single' video.id %}">
                        {% if video.thumbnail %}
                        <img class="mypage_thumbnail" src="{{ video.thumbnail.url }}" alt="{{ video.title }}">
                        {% else %}
                        <img class="mypage_thumbnail" src="{% static 'tube/img/no-img.png' %}" alt="{{ video.title }}">
                        {% endif %}
                    </a>

                    <div class="s_video_sub_inner">
                        <div class="s_video_sub_inner_left">
                            {% if video.user.usericon %}
                            <a href="{% url 'tube:usersingle' video.user.id %}"><img class="index_usericon" src="{{ video.user.usericon.url }}" alt="icon"></a>
                            {% else %}
                            <a href="{% url 'tube:usersingle' video.user.id %}"><img class="index_usericon" src="{% static 'tube/img/non_usericon.png' %}" alt="{{ icon }}"></a>
                            {% endif %}
                        </div>

                        <div class="s_video_sub_inner_right">
                            <div class="video_title">{{ video.title }}</div>
                            <div>{{ video.user.handle_name }} </div>

                            {# {% comment %} #}
                            <div class="video_value">
                                <span class="v_value_span"><i class="far fa-play-circle"></i>{{ video.views|intcomma }}</span>
                                <span class="v_value_span"><i class="far fa-comment"></i>{{ video.num_comments }}</span>
                                <span class="v_value_span"><i class="far fa-list-alt"></i>{{ video.num_mylists }}</span>
                            </div>
                            {# {% endcomment %} #}


                            <div>{{ video.dt|date:"Y年m月d日 H時i分s秒" }}</div>
                            <div>{{ video.category }}</div>
                        </div>
                    </div>
                </div>
                {% empty %}
                <div class="mypage_video_content"><p>投稿した動画はありません。</p></div>
                {% endfor %}
            </div>
        
        </div>







    </div>
    {% else %}
    <div>ユーザーが見つかりませんでした</div>
    {% endif %}

{% endblock %}

